"""The writer: the cortex engine behind the pipeline's old AI interface.

There is no external model, no API key and no paid service anywhere in this file.
`CortexWriter` keeps the same shape the pipeline already expects — `enabled`,
`generate()`, `health()`, `auth_errors` — so the publishing flow does not change,
but every article now comes from the local cortex engine and carries a complete SEO
plan with it.

`auth_errors` stays in the interface on purpose: it is permanently empty, which is
the honest signal that nothing in the writing path can fail for lack of a key.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime

from .cortex.engine import ENGINE_NAME, ENGINE_VERSION, CortexEngine
from .cortex.types import ArticleDraft as CortexDraft
from .cortex.types import ArticleRequest, SeoPlan
from .errors import ContentRejected, DuplicateContent
from .log import get_logger
from .seo import planner as seo_planner
from .seo.audit import summary as audit_summary

log = get_logger("writer")

PROVIDER = "cortex"
MODEL = f"{ENGINE_NAME} {ENGINE_VERSION}"


@dataclass
class ArticleDraft:
    """The legacy draft shape the renderer and the state ledger consume."""

    headline: str
    body_html: str
    meta_description: str = ""
    category: str = ""
    tags: tuple[str, ...] = ()
    key_points: list[str] = field(default_factory=list)
    faq: list[dict] = field(default_factory=list)
    words: int = 0
    quality_score: int = 0
    confidence: float = 0.0
    provider: str = PROVIDER
    model: str = MODEL
    ai_generated: bool = False           # nothing is generated by an external model
    machine_written: bool = True
    engine: str = MODEL
    timings: dict = field(default_factory=dict)
    stats: dict = field(default_factory=dict)
    seo: SeoPlan | None = None
    sections: tuple = ()
    tldr: tuple[str, ...] = ()
    outline: list[str] = field(default_factory=list)
    readability: dict = field(default_factory=dict)
    sentiment: dict = field(default_factory=dict)
    entities: tuple[str, ...] = ()
    keywords: dict = field(default_factory=dict)
    focus_keyword: str = ""
    rejection: str = ""
    cortex: CortexDraft | None = field(default=None, repr=False, compare=False)

    @property
    def dek(self) -> str:
        return self.meta_description

    def as_cortex(self) -> CortexDraft:
        """The engine's own draft record, which the SEO planner consumes."""
        if self.cortex is not None:
            return self.cortex
        return CortexDraft(headline=self.headline, body_html=self.body_html,
                           dek=self.meta_description, meta_description=self.meta_description,
                           category=self.category, tags=self.tags, sections=self.sections,
                           faq=tuple((item.get("question", ""), item.get("answer", ""))
                                     for item in self.faq),
                           tldr=self.tldr, keywords=self.keywords, outline=self.outline,
                           words=self.words, quality_score=self.quality_score,
                           readability=self.readability, sentiment=self.sentiment,
                           entities=self.entities, confidence=self.confidence,
                           machine_written=True, engine=self.engine, stats=self.stats)


@dataclass
class GenerationRequest:
    """Everything the writer needs. Temperature and token limits are kept as no-ops
    so old configuration files still load; the engine is deterministic by design."""

    title: str
    text: str
    source: str = ""
    url: str = ""
    published: str = ""
    related: list[str] = field(default_factory=list)
    categories: list[str] = field(default_factory=list)
    category: str = ""
    site: str = ""
    target_words: int = 650
    min_words: int = 400
    max_source_chars: int = 12000
    temperature: float = 0.0             # accepted and ignored
    max_output_tokens: int = 0           # accepted and ignored
    prompt_template: str = ""            # accepted and ignored
    feedback: str = ""
    tone: str = "news"
    audience: str = ""
    internal_links: list[dict] = field(default_factory=list)


class CortexWriter:
    """Deterministic, offline article writer with a built-in quality gate."""

    def __init__(self, settings, state=None, *, engine: CortexEngine | None = None) -> None:
        self.s = settings
        self.state = state
        self.engine = engine or CortexEngine(
            grade_target=float(settings.get("writer.grade_target",
                                            settings.get("ai.grade_target", 12.0))),
            rewrite=bool(settings.get("writer.rewrite", True)),
            min_facts=int(settings.get("writer.min_facts", 3)),
            min_confidence=float(settings.get("writer.min_confidence", 0.30)),
            max_quality_passes=int(settings.get("writer.quality_passes", 2)),
            novelty_threshold=float(settings.get("writer.novelty_threshold", 0.42)),
            supported_languages=tuple(str(item) for item in settings.get(
                "writer.languages", ["en"])),
        )
        self.auth_errors: dict[str, str] = {}
        self.enabled = bool(settings.get("writer.enabled", settings.get("ai.enabled", True)))
        self.last_stats: dict = {}
        self.written = 0
        self.rejected = 0

    # ------------------------------------------------------------------ writing

    def generate(self, req: GenerationRequest) -> ArticleDraft | None:
        """Write one article, or None when the source cannot support one."""
        if not self.enabled:
            self.rejected += 1
            return None

        source_text = (req.text or "")[: max(4000, req.max_source_chars)]
        if not source_text.strip():
            log.warning("Writer: empty source text for %r", req.title[:60])
            return None
        cortex_req = ArticleRequest(
            title=req.title, text=source_text, source=req.source, url=req.url,
            published=req.published, related=list(req.related),
            category=req.category or (req.categories[0] if req.categories else ""),
            target_words=req.target_words, min_words=req.min_words,
            tone=req.tone or "news", site_name=req.site or self.s.site_name,
            internal_links=list(req.internal_links),
        )
        try:
            draft = self.engine.write(cortex_req,
                                      published_titles=self.published_titles(),
                                      published_bodies=self.published_bodies())
        except DuplicateContent as exc:
            self.rejected += 1
            log.info("Writer: duplicate story skipped (%s)", exc)
            return None
        except ContentRejected as exc:
            self.rejected += 1
            log.warning("Writer rejected %r: %s", req.title[:50], exc)
            return None

        self.written += 1
        self.last_stats = dict(draft.stats)
        return ArticleDraft(
            headline=draft.headline, body_html=draft.body_html,
            meta_description=draft.meta_description, category=draft.category,
            tags=draft.tags, key_points=list(draft.tldr),
            faq=[{"question": question, "answer": answer} for question, answer in draft.faq],
            words=draft.words, quality_score=draft.quality_score, confidence=draft.confidence,
            timings=draft.timings, stats=draft.stats, sections=draft.sections,
            tldr=draft.tldr, outline=draft.outline, readability=draft.readability,
            sentiment=draft.sentiment, entities=draft.entities, keywords=draft.keywords,
            cortex=draft,
        )

    def published_titles(self, *, limit: int = 250) -> list[str]:
        """Titles already on the blog, so the novelty gate has something to compare to."""
        titles: list[str] = []
        if self.state is None:
            return titles
        try:
            for record in self.state.published_records()[:limit]:
                title = str(record.get("title", ""))
                if title:
                    titles.append(title)
        except Exception as exc:            # a corrupt ledger must not stop publishing
            log.debug("Writer: could not read published titles: %s", exc)
        return titles

    def published_bodies(self, *, limit: int = 40) -> list[str]:
        """Recent post bodies are not stored, so only titles feed the novelty check."""
        return []

    # ---------------------------------------------------------------------- SEO

    def plan_seo(self, draft: ArticleDraft, *, category: str = "", post_url: str = "",
                 images: list | None = None, related_posts: list[dict] | None = None,
                 published_slugs: list[str] | None = None, source_urls: list[str] | None = None,
                 published: datetime | None = None) -> SeoPlan:
        """Full SEO plan for a finished draft: titles, schema, links and the audit."""
        images = images or []
        image_url = ""
        caption = ""
        credit = ""
        if images:
            first = images[0]
            image_url = str(first[1]) if isinstance(first, (tuple, list)) and len(first) > 1 else ""
            candidate = first[0] if isinstance(first, (tuple, list)) else None
            caption = str(getattr(candidate, "caption", "") or "")
            credit = str(getattr(candidate, "credit", "") or "")
        plan = seo_planner.plan(
            draft.as_cortex(), site_name=self.s.site_name,
            site_url=self.s.get("site.url", ""), post_url=post_url, category=category,
            author=self.s.get("site.author_name", self.s.site_name),
            author_url=self.s.get("site.author_url", ""),
            publisher_logo=self.s.get("site.logo_url", ""), image_url=image_url,
            image_caption=caption, image_credit=credit,
            related=[{"title": str(item.get("title", "")), "url": str(item.get("url", ""))}
                     for item in (related_posts or []) if item.get("url")],
            published_slugs=list(published_slugs or []),
            published=published or datetime.now(UTC),
            language=str(self.s.get("site.language", "en")),
            twitter_handle=str(self.s.get("social.twitter_handle", "")),
            facebook_app=str(self.s.get("social.facebook_app_id", "")),
            source_urls=[url for url in (source_urls or []) if url],
            search_url=self.s.get("site.search_url", ""),
        )
        draft.seo = plan
        return plan

    # ------------------------------------------------------------------- health

    def health(self) -> dict:
        """Reported in every run summary: the engine, not a list of API keys."""
        return {
            "engine": MODEL, "enabled": self.enabled, "provider": PROVIDER,
            "requires_api_key": False, "cost": "free",
            "articles_written": self.written, "articles_rejected": self.rejected,
            "grade_target": self.engine.grade_target,
            "quality_passes": self.engine.max_quality_passes,
            "novelty_threshold": self.engine.novelty_threshold,
            "gazetteer_entries": len(self.engine.gazetteer().entries),
            "auth_errors": {},
        }

    def describe(self, draft: ArticleDraft) -> str:
        """One-line human summary of what the engine did."""
        quality = draft.stats.get("quality", {})
        return (f"{draft.words} words · quality {draft.quality_score} · "
                f"confidence {draft.confidence:.2f} · grade "
                f"{quality.get('grade', 0):.1f} · outline {'/'.join(draft.outline)}")


def build_writer(settings, state=None) -> CortexWriter:
    """Factory used by the pipeline (same call shape as the old AI router)."""
    return CortexWriter(settings, state)


def seo_summary(plan: SeoPlan | None) -> str:
    """Short SEO audit line for logs and the run report."""
    if plan is None:
        return "no SEO plan"
    failing = plan.failing_checks()
    head = f"SEO {plan.score}/100"
    return f"{head}; {len(failing)} check(s) to fix" if failing else f"{head}; all checks passed"


__all__ = ["ArticleDraft", "GenerationRequest", "CortexWriter", "build_writer",
           "seo_summary", "audit_summary", "SeoPlan", "PROVIDER", "MODEL"]
